name: accordion
description: An expandable Flutter widget list where each item can be expanded or collapsed simply by clicking on the header.
version: 2.5.2
homepage: https://www.vulcansoft.com
repository: https://github.com/GotJimmy/accordion

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  scroll_to_index: ^3.0.1

flutter:
  uses-material-design: true
dev_dependencies:
  flutter_lints: ^2.0.1
